### ISSUE TITLE
Auto Updating Course Data

### ISSUE THREAD

**Issue by 123joshuawu** [Apexal/orca#9]
Saw the comment on Reddit re: auto-updating course data.

Could go two routes:
1) Periodically call the production `"/{semester_id}/sections/update"` API route
2) Periodically run the scraper and insert the data into the production database

Both would need to make sure that if the insert fails due to some error (violated SQL constraint, parsing error, ...), the transaction is rolled back and we are notified of the failure (maybe creating a Github Issue). 

Then we can probably also add a `last_updated` timestamp so users know how recent the data is.

**Comment by Apexal** [comment]
Thanks for opening. I think the entire DB update takes place in one transaction, at least I tried to make sure it does. The route will return an error HTTP status if anything goes wrong but won't currently give a specific message I believe. I need to learn more about error handling in FastAPI to be honest. Do you know of the simplest way we could send that request to the route and send a webhook or similar on failure? Does GitHub Actions have things like that?

**Comment by 123joshuawu** [comment]
Yeah, I'll get a quick workflow running. 

Using option 1 you'll have to refer to the production logs to debug the issue unless the error message is returned in the API response. Using option 2 would give the workflow access to the error and but requires more instrumentation.

**Comment by Apexal** [comment]
Great. I'll look into returning error messages without forfeiting security. I added you as a repo collaborator so you have direct access!
